volumes:
  db:

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE = robomania
      - MONGO_INITDB_ROOT_USERNAME = root
      - MONGO_INITDB_ROOT_PASSWORD = root
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    hostname: mongo
    networks:
      - robomania_database
      - default
    deploy:
      resources:
        limits:
          memory: 4gb

networks:
  robomania_database:
    driver: bridge
  front:
    name: host
    external: true
