[project]
name = "robomania"
version = "0.0.1"
description = "Bot for use on Domeq Krk discord server"
requires-python = ">=3.10"
dependencies = [
    "disnake == 2.5.1",
    "python-dotenv == 0.20.0",
    "facebook-scraper == 0.2.56",
    "motor[srv] == 3.0.0",
    "Pillow == 9.1.1",
    "pytesseract == 0.3.9",
    "aiohttp == 3.8.1",
    "pymongo == 4.1.1",
    "click == 8.1.3",
]

[project.optional-dependencies]
dev = [
    "autopep8",
    "flake8",
    "pytest",
    "mongomock-motor",
    "Faker",
    "isort",
    "mypy",
    "pytest-asyncio",
    "pytest-httpserver",
    "pytest-mock",
    "pytest-dotenv",
]

[build-system]
requires = ["setuptools >= 58.1"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
asyncio_mode = "strict"
addopts = "--cov=src/robomania --cov-report html --cov-report xml:cov.xml"


[tool.mypy]
python_version = "3.10"
show_error_codes = true
ignore_missing_imports = true

[tool.autopep8]
max_line_length = 79
in-place = true
recursive = true
aggressive = 3

[tool.coverage.run]
source = ["src/robomania"]
omit = ["src/robomania/cogs/tester.py", "src/robomania/cogs/planner.py"]

[tool.coverage.report]
skip_empty = true
exclude_lines = [
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "def __str__",
    "def __repr__",
    "pragma: no cover",
    "@click",
    "if Config.debug:"
]
