name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ["self-hosted"]
  #   steps:
  #     - name: "Run tests"
  deploy:
    runs-on: ["self-hosted", "Linux"]
    environment: deployment
    env:
      VENV: "~/.robomania/.venv"
      ROBOMANIA_CWD: ~/.robomania
      ROBOMANIA_PY: "$VENV/bin/python"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Create virtual environment"
        run: |
          [ ! -d $VENV ] && virtualenv $VENV
      - name: "Build bot"
        run: |
          rm -rf dist
          python3 -m build
      - name: "Install bot"
        run: |
          $VENV/bin/pip install $(find ~+ -name '*.whl')
      - name: Run as service
        shell: powershell
        run: ./setup.ps1
