name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ["self-hosted"]
  #   steps:
  #     - name: "Run tests"
  deploy:
    runs-on: ["self-hosted", "Linux"]
    environment: deployment
    env:
      VENV: "${{ secrets.HOME }}/.robomania/.venv"
      ROBOMANIA_CWD: "${{ secrets.HOME }}/.robomania"
      ROBOMANIA_PY: "${{ secrets.HOME }}/.robomania/.venv/bin/python"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Create virtual environment"
        shell: pwsh
        run: |
          cd ${{ env.ROBOMANIA_CWD }}
          if (-not(Test-Path -Path .venv)) {
            virtualenv .venv
          }
      - name: "Build bot"
        run: |
          pip install build
          rm -rf dist
          python3 -m build
      - name: "Turn off bot"
        if: ${{ always() }}
        run: |
          systemctl stop robomania
      - name: "Install bot"
        run: |
          ${{ env.VENV }}/bin/pip install $(find ~+ -name '*.whl')
      - name: Run as service
        shell: pwsh
        run: ./setup.ps1
