name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ["self-hosted"]
  #   steps:
  #     - name: "Run tests"
  deploy:
    runs-on: ["self-hosted", "Linux"]
    environment: deployment
    env:
      VENV: "~/.robomania/.venv"
      VENV_PY: "$VENV/bin/python"
      VENV_PIP: "$VENV/bin/pip"
      ROBOMANIA_CWD: ~/.robomania
      ROBOMANIA_PY: "$VENV_PY"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Create virtual environment"
        run: |
          cd ${{ env.ROBOMANIA_CWD }}
          [ ! -d ${{ env.VENV }} ] && virtualenv .venv
      - name: "Build bot"
        run: |
          ${{ env.VENV_PIP }} install build
          rm -rf dist
          ${{ env.VENV_PY }} -m build
      - name: "Install bot"
        run: |
          ${{ env.VENV_PIP }} install $(find ~+ -name '*.whl')
      - name: Run as service
        shell: powershell
        run: ./setup.ps1
